### ISSUE TITLE
RFM2PI attiny85

### ISSUE THREAD

**Issue by WilcoE** [mharizanov/RFM2Pi#10]
RFM2PI v1 send no ack to nodes, Serial output gives ack messages but this messages is not recieved by nodes. Can't find any source code for the RFM2PI Atttiny so can't bug hunt the problem.

**Comment by glynhudson** [comment]
There are known issues with the software serial emulation in the attiny.
This is why we moved to ATmega328 with hardware serial. Source code for
attiny is found here:
https://github.com/mharizanov/RFM2Pi/blob/master/firmware/RFM2Pi_RF12_Demo/TinySensor_RF12_Demo/TinySensor_RF12_Demo.ino

-sent from my mobile device
