### ISSUE TITLE
serial.pl creates GET requests with a trailing comma

### ISSUE THREAD

**Issue by lafrech** [mharizanov/RFM2Pi#2]
Hi.

When using the perl gateway, I get GET requests with a trailing comma, which leads emoncms to create two inputs for the node.

I think the following piece of code was made to avoid this, but I had to make that change to make it work as expected.

@@ -89,13 +95,15 @@ while ($continue) {
           my $msubs ="";
           for(my $i=1; $i<@values; $i+=2){
             $msubs .= $values[$i] + $values[$i+1]*256;
-            if($i) {$msubs .= ","};
-            if($i!=@values-2) {$msubs .= ","};
        }

Or perhaps I misunderstand the whole thing... But anyway, having $i between 1 and values, "if($i)" can't be false.

I hope I'm making myself clear.

Thanks for the good work, by the way.

Have a nice day.
## 

Jérôme

**Comment by lafrech** [comment]
I should have previewed. The minus and plus from the diff were turned into list bullets... Sorry about that. 

Guess you get the meaning, anyway.

**Comment by mharizanov** [comment]
Hi,
Thanks, these were early tests, the support for RFM2Pi board is now
in-built in the "modular" version of emoncms. The perl script also fails on
ACKs, but it is a good example to get you started.
http://wiki.openenergymonitor.org/index.php?title=Raspberry_Pi

Best,
Martin

**Comment by lafrech** [comment]
Solved, I guess : cb2daa0d4a24df0b6100649dd28ba3716eab8548
